# =========================
# SERVER CONFIG
# =========================
server.port=${PORT:10000}

# =========================
# MONGODB CONFIG
# =========================
mongodb+srv://phantomuser:krish05@cluster0.iyhgomg.mongodb.net/phantom?retryWrites=true&w=majority
spring.data.mongodb.database=phantom

# =========================
# OPTIONAL LOGS (for debugging)
# =========================
logging.level.org.springframework=INFO
logging.level.org.mongodb.driver=ERROR