# =========================
# SERVER CONFIG
# =========================
server.port=${PORT:10000}

# =========================
# MONGODB CONFIG
# =========================
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=catdb